# Site Params

# Fallback Twitter card image (if not set on page)
images = ["img/social.png"]

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/cue-lang/cuelang.org"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "004591905419617723008:8rmik2a7xb3"

# Which logo to use in main header
logo = "svg/logo-alpha.svg"

# Add a site-wide notification-bar
# Contents allows for markdown, leave out the button if you don't want a button
[notification]
    type = 'test'
    content = '**Note:** documentation on this site relies on CUE v0.6.0'
    [notification.button]
        link = 'https://github.com/cue-lang/cue/releases'
        icon = 'download'
        text = 'Download'


# Tags
# Color can be one of: red, orange, green, pink, purple, lila, blue, lavender

[[tags]]
name = "Ecosystem"
color = "red"
weight = 10

[[tags]]
name = "Use encodings in CUE"
color = "green"
weight = 20

[[tags]]
name = "cue command"
color = "purple"
weight = 30

[[tags]]
name = "Language"
color = "blue"
weight = 40

