# Main
[[main]]
    identifier = "docs"
    name = "文档"
    url = "/docs/"
    weight = 100
[[main]]
    identifier = "play"
    name = "操场"
    url = "/play/"
    weight = 101
[[main]]
    identifier = "community"
    name = "社区"
    url = "/community/"
    weight = 102
[[main]]
    identifier = "blog"
    name = "博客"
    url = "/Blog/"
    weight = 103

# Icons
[[icons]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/cue_lang"
    pre = "twitter"
    weight = 200
[[icons]]
    identifier = "slack"
    name = "Slack"
    url = "https://join.slack.com/t/cuelang/shared_invite/enQtNzQwODc3NzYzNTA0LTAxNWQwZGU2YWFiOWFiOWQ4MjVjNGQ2ZTNlMmIxODc4MDVjMDg5YmIyOTMyMjQ2MTkzMTU5ZjA1OGE0OGE1NmE"
    pre = "slack"
    weight = 201
[[icons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/cue-lang/cue"
    pre = "github"
    weight = 203

# CTA
[[cta]]
    identifier = "cta"
    name = "下载"
    url = "/docs/install/"
    post = "download"
    weight = 300

# Footer
[[footer]]
    identifier = "column1"
    name = "Get Started"
    url = "#"
    weight = 400
[[footer]]
    parent = "column1"
    name = "Download"
    url = "/docs/install/"
    weight = 410
[[footer]]
    parent = "column1"
    name = "Get started"
    url = "/docs/get-started/"
    weight = 411
[[footer]]
    parent = "column1"
    name = "Reference Documentation"
    url = "/docs/references/"
    weight = 412

[[footer]]
    identifier = "column2"
    name = "Community"
    url = "#"
    weight = 401
[[footer]]
    parent = "column2"
    name = "The CUE community"
    url = "/community/"
    weight = 420
[[footer]]
    parent = "column2"
    name = "Contributing"
    url = "/docs/contribution-guidelines/"
    weight = 421
[[footer]]
    parent = "column2"
    name = "Code of conduct"
    url = "/docs/contribution-guidelines/code-of-conduct/"
    weight = 422

[[footer]]
    identifier = "column3"
    name = "About"
    url = "#"
    weight = 402
[[footer]]
    parent = "column3"
    name = "About CUE"
    url = "/docs/about/"
    weight = 430
[[footer]]
    parent = "column3"
    name = "Blog"
    url = "/blog/"
    weight = 431

[[footer]]
    identifier = "column4"
    name = "Connect"
    url = "#"
    weight = 403
[[footer]]
    parent = "column4"
    name = "Twitter"
    url = "https://twitter.com/cue_lang"
    weight = 440
[[footer]]
    parent = "column4"
    name = "Slack"
    url = "https://join.slack.com/t/cuelang/shared_invite/enQtNzQwODc3NzYzNTA0LTAxNWQwZGU2YWFiOWFiOWQ4MjVjNGQ2ZTNlMmIxODc4MDVjMDg5YmIyOTMyMjQ2MTkzMTU5ZjA1OGE0OGE1NmE"
    weight = 441
[[footer]]
    parent = "column4"
    name = "GitHub"
    url = "https://github.com/cue-lang/cue"
    weight = 442

# Legal
[[legal]]
    identifier = "copyright"
    name = "版权"
    url = "#"
    weight = 500
[[legal]]
    identifier = "privacy"
    name = "隐私政策"
    url = "#"
    weight = 501
